### ISSUE TITLE
[Feature] Home Web Page

### ISSUE THREAD

**Issue by AuroTB** [RoBorregos/roborregos-web#110]
Implement these changes on the "Home" page following the [new design](https://docs.google.com/document/d/1pcM8HLVA03Eg6IpAgGLFKJohMMDzpOWneZOUIMtY2cs/edit#heading=h.k8s5mlltkh3):

Components to develop:
1. Mission/vision component
2. [Carousel](https://www.npmjs.com/package/react-material-ui-carousel) of nice photos

Before PR check that:
- [ ] All content and UI follow the Canva design.
- [ ] All views are responsive

**Comment by zJuarez** [comment]
waiting on images for carousel. branch feature/home has already a final mision-vision section and a working (needing images and styling) carousel
