### ISSUE TITLE
[Feature] [Back-end] Host mail service in static PHP server

### ISSUE THREAD

**Issue by AuroTB** [RoBorregos/roborregos-web#111]
Develop and make the mail service static for "join us" requests (in members page) and "contact us" requests (in support us page).

Candidate's "join us" request info:
{
      message: emailBody,
      from_name: this.name.value,
      reply_to: `${this.matricualtionNumber.value}@itesm.mx`,
      position: selectedPosition.title,
}
![image](https://user-images.githubusercontent.com/25405578/120403659-3f0f7900-c30a-11eb-91e4-a71ef8fd3fdd.png)

Support us "contact us" info:
{
      message: emailBody,
      from_name: name,
      reply_to: email,
      send_copy: sendCopy, <--- bool
}
![image](https://user-images.githubusercontent.com/25405578/120403643-328b2080-c30a-11eb-9945-4ae9aee94dd8.png)

**Comment by AuroTB** [comment]
I'll be in charge of the html to generate the messages.

**Comment by Josecisneros001** [comment]
![Captura de pantalla de 2021-06-16 23-57-00](https://user-images.githubusercontent.com/36351179/122334223-ff967e80-cefe-11eb-95a0-92bf1f2a709d.png)
![Captura de pantalla de 2021-06-16 23-56-50](https://user-images.githubusercontent.com/36351179/122334229-00c7ab80-ceff-11eb-8fb6-dace70b5bb16.png)
![Captura de pantalla de 2021-06-16 23-56-37](https://user-images.githubusercontent.com/36351179/122334230-00c7ab80-ceff-11eb-82bf-7486cc2a1cee.png)
![Captura de pantalla de 2021-06-16 23-42-54](https://user-images.githubusercontent.com/36351179/122334231-00c7ab80-ceff-11eb-9ec1-7a061cc2bba8.png)
![Captura de pantalla de 2021-06-16 23-06-48](https://user-images.githubusercontent.com/36351179/122334232-01604200-ceff-11eb-8ac3-d2914e166476.png)
