### ISSUE TITLE
Se añaden Unit Tests a /Home

### ISSUE THREAD

**Issue by RicardoChapaRomero** [RoBorregos/roborregos-web#28]
- Se añaden Unit Tests a /Home

**Comportamiento deseado**
- Los componentes de /Home tiene Unit Tests por función en cada archivo.

**Criterios de aceptación**
- [ ] Se cumple con los estilos de código de Flow-Eslint y no existe error de compilación.
- [ ] Todos los Unit Tests propuestos pasan de manera esperada.

**Comment by JamirLeal** [comment]
Unit test sobre responsividad, paths, carga de componentes
