### ISSUE TITLE
En /Home, se añade a Teknik comp patrocinador en la sección de sponsors

### ISSUE THREAD

**Issue by RicardoChapaRomero** [RoBorregos/roborregos-web#4]
- En /Home, se añade a Teknik comp patrocinador en la sección de sponsors

**Comportamiento deseado**
- Se añade la imagen de Teknik en la sección de patrocinadores al fondo de la sección /Home

**Criterios de aceptación**
- [x] El código sigue los [estilos de código preestablecidos](https://google.github.io/styleguide/)
- [x] La pagina se comporta de forma responsiva
- [x] Se añade una imagen sin fondo de Teknik al mismo nivel y tamaño que los demás patrocinadores

**Comment by AuroTB** [comment]
lo cambié a 1 porque sí estuvo facilillo jajaja
