### ISSUE TITLE
En /Contact, se cambia la titulo de introduccion a los paquetes de sponsor del equipo 

### ISSUE THREAD

**Issue by RicardoChapaRomero** [RoBorregos/roborregos-web#51]
- En /Contact, se cambia la titulo de introduccion a los paquetes de sponsor del equipo 

**Comportamiento deseado**
- Se cambia el titulo de la imagen por **RoBorregos Sponsor Packages**
![Screen Shot 2020-10-26 at 17 47 49](https://user-images.githubusercontent.com/47112298/97240590-47bc3180-17b4-11eb-9e2c-4b88583bd7fa.png)

**Criterios de aceptación**
- [ ] La pagina se comporta de forma responsiva

**Comment by AuroTB** [comment]
#### Que onda, tengo varios comentarios:
- Después de hablar con CLP decidí cambiar el contenido del banner tmbn, además de los paquetes de sponsor con su respectivo contenido actualizado (puedes verlo en la branch _feature/ContactContent_).
- Vi que había algo para traducir los paquetes a español, **el UI no me gusta** pero **se me hace una muy buena idea**; aún así, me gustaría poder **implementarlo para toda la página** antes de sólo implementarlo ahí bn random.
- La sección de donaciones se puede cambiar a algo como lo que tenemos en la [otra pag](https://roborregos.github.io/patrocinadores): 
![image](https://user-images.githubusercontent.com/25405578/97479132-83234100-1917-11eb-8efd-a33d0f7c536d.png)
- Eliminaría lo de los proyectos de amero abajo, porque ya son muchas cosas; sería mejor implementar una nueva tab/página que se enfoque en presentar los proyectos activos del semestre/año.
- Con todos estos cambios cambiaría el nombre de la tab a **"Support Us / Donate"**
