### ISSUE TITLE
[Hosting] Obtain our own domain!

### ISSUE THREAD

**Issue by AuroTB** [RoBorregos/roborregos-web#69]
- Setup domain roborregos.mx
- Obtain SSL for web page
- Configure Deployment pipeline

**Comment by AuroTB** [comment]
The roborregos.mx domain is not available in the Hostinger plan we want to buy.
Currently contacting Teknik to see if they can free roborregos.com for us to use it.

**Comment by Josecisneros001** [comment]
After speaking with our latest web sponsor, the domain owner of "roborregos.com", the ownership transfer process is already in progress and will be available on 01/19/2021. So apparently we will continue to use roborregos.com.
