### ISSUE TITLE
En /Members, se arregla la inserción de botones de LinkedIn y Github de los miembros

### ISSUE THREAD

**Issue by RicardoChapaRomero** [RoBorregos/roborregos-web#8]
- En /Members, se arregla la inserción de botones de LinkedIn de los miembros

**Comportamiento deseado**
- Se añaden los iconos de LinkedIn y Github al Grid Member de Chapa con sus respectivos links
- Se cambia el link del icono de Github de Ruiz (actualmente esta el Github de Chapa referenciado)

**Criterios de aceptación**
- [x] Se siguen los [formatos de código preestablecidos](https://google.github.io/styleguide/)
- [x] Se añaden los botones con sus respectivos links.
- [x] Los links funcionan correctamente

**Comment by AuroTB** [comment]
@RicardoChapaRomero no encuentro tu linkedin en los [registros](https://docs.google.com/spreadsheets/d/1Hw8PF6q8g7-jmp-Tbomvno0e00zRh0pgCZjTFXFlILk/edit#gid=0), plz agrégalo o pásalo por whatsapp jaja

Igualmente, el error fue al momneto de pasar la info del csv al script (no hay ningún error extraño o bug) entonces era solo de cambiar el json. Lo puse como un hotfix!
